version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      compatible:
        update-types: [minor, patch]
  - package-ecosystem: pub
    directory: /flutter
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      compatible:
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
