name: Flutter Tag Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

permissions:
  contents: read

concurrency:
  group: flutter-tag-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
  publish-release:
    needs: [run-flutter-tag-build]
    uses: ./.github/workflows/release-publish.yml
    permissions:
      contents: write
    with:
      upload-tag: ${{ github.ref_name }}
